naming:
  middle_names:
    enabled: true
    chance_percentage: 20
leashing:
  villager: true
  wandering_trader: true
  zombie_villager: false
discordsrv:
  # a channel defined in discordsrv config
  # just leave it as "global" if you don't know what this is
  # set to an empty string "" to disable
  channel_name: global

# How much food and saturation villagermeat will restore when eaten.
#
# For comparison, vanilla Minecraft steak is worth:
# → 8 hunger (4 drumsticks)
# → 12.8 saturation points
#
# See also: https://minecraft.wiki/w/Hunger
villagermeat:
  food_points: 10 # 1 full drumstick in your hunger bar represents 2 hunger points
  saturation_points: 14


names:
  first:
    - Aaliyah
    - Aary
    - Abigail
    - Adalyn
    - Aiden
    - Akrat
    - Alexander
    - Amelia
    - Aria
    - Ariana
    - Asher
    - Aubrey
    - Aurora
    - Ava
    - Avery
    - Baka
    - Barry
    - Benjamin
    - Berry
    - Billzo
    - Birch
    - Blackberry
    - Blueberry
    - Blunt
    - Bovine
    - Buwa
    - Caden
    - Caleb
    - Cameron
    - Camilla
    - Carson
    - Carter
    - Cary
    - Chambi
    - Charlie
    - Charlotte
    - Chloe
    - Chris
    - Chunk
    - Cocanine
    - Colton
    - Cranberry
    - Dairy
    - Daniel
    - Diamond
    - Earring
    - Elena
    - Eliana
    - Elijah
    - Ella
    - Ellie
    - Emerald
    - Emilia
    - Emily
    - Emma
    - Espion
    - Ethan
    - Evelyn
    - Everly
    - Ezra
    - Fairy
    - Ferry
    - Fynch
    - Gabriel
    - Gary
    - Gerry
    - Glory
    - Goldie
    - Grayson
    - Hairy
    - Hannah
    - Harper
    - Harry
    - Henry
    - Holden
    - Honag
    - Hrrm
    - Hurrm
    - Hurrrm
    - Isaac
    - Isabella
    - Isaiah
    - Isla
    - Jack
    - Jackie
    - Jackson
    - Jakob
    - James
    - Jasper
    - Jayce
    - Jayden
    - Jerry
    - Joe
    - Julian
    - Karen
    - Keri
    - Kinsley
    - Larry
    - Layla
    - Lazy
    - Leah
    - Leo
    - Levy
    - Liam
    - Lila
    - Lily
    - Lincoln
    - Logan
    - Lucas
    - Luna
    - Madelyn
    - Madison
    - Malcolm
    - Mary
    - Mason
    - Matteo
    - Matthew
    - Maverick
    - Maya
    - Merry
    - Mia
    - Michael
    - Mila
    - Miles
    - Muhammad
    - Netherite
    - Noah
    - Nora
    - Nova
    - Nugget
    - Oliver
    - Olivia
    - Owen
    - Owosome
    - Paisley
    - Parry
    - Penelope
    - Quartz
    - Raspberry
    - Rat
    - Riley
    - Ryan
    - Samuel
    - Sarah
    - Sarmii
    - Scarlett
    - Sebastian
    - Sherry
    - Smith
    - Sniki
    - Sophia
    - Sorry
    - Suwa
    - Terry
    - Tobias
    - Toby
    - Vikkeur
    - Vlad
    - Walrus
    - Wary
    - Weedy
    - William
    - Wyatt
    - Yakson
    - Yeti
    - Yumsome
    - Zoe
  last:
    - Aardvark
    - Ashwin
    - Bakalarachi
    - Baron
    - Bass
    - Bee
    - Blunt
    - Bovine
    - Caterpillar
    - Chess
    - Christ
    - Class
    - Claus
    - Cube
    - Death
    - Drugglez
    - Duck
    - Dukk
    - Ekto
    - Ektobawaeur
    - Forg
    - Garfield
    - Gas
    - Goldfish
    - Golem
    - Harka
    - Heksagon
    - Hexagon
    - Hmm
    - Hrm
    - Hurm
    - Inbred
    - Ingot
    - Ironforests
    - Jackass
    - Jasperlandtwo
    - Larachi
    - Mass
    - Moolah
    - Nervegas
    - Newrhodes
    - Nuke
    - Oolah
    - Oolahist
    - Owo
    - Plutonium
    - Porkchop
    - Poutine
    - Puzic
    - Qwakk
    - RandumPerson314
    - Rozman
    - Rubik
    - Sandals
    - Sheppard
    - Smith
    - Snikigung
    - Snowman
    - Staline
    - Sugar
    - Thorium
    - Tobytopia
    - Toothbrush
    - Trespass
    - Uranium
    - Wambi
    - Weeeeed
    - Woveyad
    - Yeti