name: VillagerMeat
description: >
  ยง3Automatically gives villagers names. When villagers die, a death message
  will be broadcasted for them. But don't be too sad; the villagers drop villager
  meat after all. Delicious, nutritious, and chicken flavoured.
  This plugin lets you abuse and mistreat villagers to your sadistic heart's content!
version: '${project.version}'
website: https://github.com/SeriousGuy888/BillzoVillagers
main: io.github.seriousguy888.villagermeat.Main
api-version: 1.21
authors: [ SeriousGuy888 ]
softdepend: [ DiscordSRV ]
commands:
  toggle_villager_death_messages:
    description: Toggle seeing villager death messages in chat.
