name: BillzoVillagers
version: '${project.version}'
main: io.github.seriousguy888.billzovillagers.BillzoVillagers
api-version: 1.17
authors: [ SeriousGuy888 ]
description: Enslave and abuse villagers to your sadistic heart's content!
commands:
  villager:
    description: this is a command
    usage: /<command>
    permission: billzovillagers.villager