name: BillzoVillagers
description:
  Enslave and abuse villagers to your sadistic heart's content!
  Also villagers get names and death messages.
version: '${project.version}'
website: https://github.com/SeriousGuy888/BillzoVillagers
main: io.github.seriousguy888.billzovillagers.BillzoVillagers
api-version: 1.18
authors: [ SeriousGuy888 ]
softdepend: [ DiscordSRV ]
commands:
  toggle_villager_death_messages:
    description: Toggle seeing villager death messages in chat.
    aliases:
      - toggle_vdm
      - vdm
      - villager_death_messages