name: BillzoVillagers
description: Enslave and abuse villagers to your sadistic heart's content!
version: ${project.version}
author: SeriousGuy888
main: me.billzo.billzovillagers.BillzoVillagers
api-version: 1.17
commands:
  villager:
    description: this is a command
    usage: /<command>
    permission: billzovillagers.villager